- Add User entity;
SviatoslavTataryn/book-store pull request #7
Opened 2024-06-30 19:36 UTC by SviatoslavTataryn

- Add the required DTOs and mapper;
- Add AuthenticationController;
- Add FieldMatch annotation;
- Add GlobalExceptionHandler.

2024-07-01 08:38 UTC, Elena-Bruyako requested changes
Well done! Let's fix some comments

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +@Table(name = "Users")
```suggestion
@Table(name = "users")
```

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @Column(nullable = false, unique = true)
```suggestion
    @Column(nullable = false)
```

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +        if (authenticationService.authenticate(requestDto)) {
```suggestion
        if (userRepository.existsByEmail(requestDto.email())) {
            throw new RegistrationException(
                    String.format("User with this email: %s already exists", requestDto.email())
            );
        }
```

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/AuthenticationService.java
> +        return (user.isPresent() && user.get().getPassword().equals(requestDto.password()));
You actually don't need this logic (see the UserServiceImpl)

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/validation/FieldMatch.java
> +
```suggestion
```

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/validation/PasswordValidator.java
> +
```suggestion
        return Objects.equals(firstObj, secondObj);
```

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: firstName
```suggestion
                  name: first_name
```

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: lastName
```suggestion
                  name: last_name
```

2024-07-01 08:38 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: shippingAddress
```suggestion
                  name: shipping_address
```

Read about naming convention

2024-07-04 06:02 UTC, Elena-Bruyako requested changes
left some comments

2024-07-04 06:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, unique = true)
```

2024-07-04 06:02 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/validation/PasswordValidator.java
> +        return Objects.equals(firstObj, secondObj);
Previous implementation was almost correct (revert)
```suggestion
        final Object firstObj = new BeanWrapperImpl(value).getPropertyValue(firstFieldName);
        final Object secondObj = new BeanWrapperImpl(value).getPropertyValue(secondFieldName);
        return Objects.equals(firstObj, secondObj);
```

2024-07-04 14:28 UTC, sarakhmen approved these changes

2024-07-28 16:41 UTC, merged