Hw spring boot security
SviatoslavTataryn/book-store pull request #8
Opened 2024-07-26 19:49 UTC by SviatoslavTataryn

2024-07-27 08:18 UTC, Elena-Bruyako requested changes
Good job. Let's improve it

2024-07-27 08:18 UTC, Elena-Bruyako commented on pom.xml
> +            <version>3.3.0</version>
```suggestion
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +
```suggestion
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +@AllArgsConstructor
Read about difference between annotations 
```suggestion
@RequiredArgsConstructor
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +                                        "/v2/api-docs/**") // дозволяє доступ до Swagger та OpenAPI
remove comment

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/AuthenticationController.java
> +@AllArgsConstructor
```suggestion
@RequiredArgsConstructor
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/AuthenticationController.java
> +    public UserResponseDto registerUser(@RequestBody UserRegistrationRequestDto requestDto
```suggestion
    public UserResponseDto registerUser(@RequestBody @Valid UserRegistrationRequestDto requestDto
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/AuthenticationController.java
> +    @PreAuthorize("hasAnyRole('USER')")
```suggestion
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/user/UserRegistrationRequestDto.java
> +        @NotNull
```suggestion
        @NotBlank
```

fot String type

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/exception/UserNotFoundException.java
> +public class UserNotFoundException extends RuntimeException {
remove

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/mapper/UserMapper.java
> +
You need only two methods

```
User toModel(UserRegistrationRequestDto user);

UserResponseDto toUserResponse(User user);
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Role.java
> +    }
```suggestion
    @Override
    public String getAuthority() {
        return name.name();
    }
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Role.java
> +public class Role {
```suggestion
public class Role implements GrantedAuthority {
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Role.java
> +    @Column(name = "name", nullable = false, unique = true)
```suggestion
    @Column(nullable = false, unique = true)
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @JoinTable(name = "user_roles",
```suggestion
    @JoinTable(name = "users_roles",
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +        return authorityList;
```suggestion
        return roles;
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    }
```suggestion
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/UserDetailsService.java
> +        implements org.springframework.security.core.userdetails.UserDetailsService {
```suggestion
public class UserDetailsService implements UserDetailsService {
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/UserDetailsService.java
> +                new UsernameNotFoundException("Can't find user by email" + email));
```suggestion
                new EntityNotFoundException("Can't find user by email" + email));
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/UserDetailsService.java
> +    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String email) {
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.email()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(requestDto.email())) {
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
> +        return userMapper.toUserResponse(savedUser);
```suggestion
        user.setPassword(passwordEncoder.encode(requestDto.password()));

        Role role = roleRepository.findByName(Role.RoleName.USER).orElseThrow(......;
        user.setRoles(Set.of(role));
        
        userRepository.save(user);
        return userMapper.toUserResponse(user);
```

2024-07-27 08:18 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/04-create-user-roles-table.yaml
> +            tableName: user_roles
```suggestion
            tableName: users_roles
```

2024-07-28 15:49 UTC, MentorMateAcademy approved these changes

2024-07-28 15:49 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstore/security/CustomUserDetailsService.java
> +
```suggestion
```

2024-07-28 16:41 UTC, merged